export const temperQuestions = [
    {
        key: 'r1',
        a: 'Animado',
        b: 'Antipático',
        c: 'Analítico',
        d: 'Adaptable',
    },
    {
        key: 'r2',
        a: 'Juguetón',
        b: 'Resentido',
        c: 'Persistente',
        d: 'Pasivo',
    },
    {
        key: 'r3',
        a: 'Sociable',
        b: 'Temeroso',
        c: 'Abnegado',
        d: 'Sumiso',
    },
    {
        key: 'r4',
        a: 'Indisciplinado',
        b: 'Aventurero',
        c: 'Considerado',
        d: 'Controlado',
    },
    {
        key: 'r5',
        a: 'Impaciente',
        b: 'Persuasivo',
        c: 'Respetuoso',
        d: 'Reservado',
    },
    {
        key: 'r6',
        a: 'Soso',
        b: 'Decidido',
        c: 'Imprevisible',
        d: 'Sin afecto',
    },
    {
        key: 'r7',
        a: 'Entusiasta',
        b: 'Autosuficiente',
        c: 'Díficil de Complacer',
        d: 'Vacilante',
    },
    {
        key: 'r8',
        a: 'Sensible',
        b: 'Positivo',
        c: 'Orgulloso',
        d: 'Taciturno',
    },
    {
        key: 'r9',
        a: 'Terco',
        b: 'Seguro',
        c: 'Argumentador',
        d: 'Desprendido',
    },
    {
        key: 'r10',
        a: 'Alegre',
        b: 'Tenaz',
        c: 'Nervioso',
        d: 'Mandón',
    },
    {
        key: 'r11',
        a: 'Cálido',
        b: 'Abierto',
        c: 'Enérgico',
        d: 'Franco',
    },
    {
        key: 'r12',
        a: 'Espontáneo',
        b: 'Confiado',
        c: 'Planificador',
        d: 'Implacable',
    },
    {
        key: 'r13',
        a: 'Hablador',
        b: 'Competitivo',
        c: 'Puntual',
        d: 'Interrumpe',
    },
    {
        key: 'r14',
        a: 'Popular',
        b: 'Introvertido',
        c: 'Ordenado',
        d: 'Contento',
    },
    {
        key: 'r15',
        a: 'Optimista',
        b: 'Inseguro',
        c: 'Fiel',
        d: 'Paciente',
    },
    {
        key: 'r16',
        a: 'Vengativo',
        b: 'Dominante',
        c: 'Adicto al trabajo',
        d: 'Tímido',
    },
    {
        key: 'r17',
        a: 'Aventurero',
        b: 'Jefe',
        c: 'Tímido',
        d: 'Atento',
    },
    {
        key: 'r18',
        a: 'Dudoso',
        b: 'Independiente',
        c: 'Intolerante',
        d: 'Amigable',
    },
    {
        key: 'r19',
        a: 'Inspirador',
        b: 'Apocado',
        c: 'Obstentoso',
        d: 'Divagador',
    },
    {
        key: 'r20',
        a: 'Convincente',
        b: 'Abstraido',
        c: 'Peresozo',
        d: 'Equilibrado',
    },
    {
        key: 'r21',
        a: 'Adorable',
        b: 'Osado',
        c: 'Bien portado',
        d: 'Emotivo',
    },
    {
        key: 'r22',
        a: 'Jovial',
        b: 'Decisivo',
        c: 'Perfeccionista',
        d: 'Deprimido',
    },
    {
        key: 'r23',
        a: 'Vivaz',
        b: 'Prepotente',
        c: 'Organizado',
        d: 'Manipulador',
    },
    {
        key: 'r24',
        a: 'Reticente',
        b: 'Temperamental',
        c: 'Sin entusiasmo',
        d: 'Escucha',
    },
    {
        key: 'r25',
        a: 'Lento',
        b: 'Testarudo',
        c: 'Resistente',
        d: 'Tolerante',
    },
    {
        key: 'r26',
        a: 'Sin ambición',
        b: 'Suspicaz',
        c: 'Indeciso',
        d: 'Precipitado',
    },
    {
        key: 'r27',
        a: 'Cordial',
        b: 'Instigador',
        c: 'Leal',
        d: 'Indiferente',
    },
    {
        key: 'r28',
        a: 'Encantador',
        b: 'No comprometido',
        c: 'Músico',
        d: 'Conciliador',
    },
    {
        key: 'r29',
        a: 'Desordenado',
        b: 'Inventivo',
        c: 'Idealista',
        d: 'Humor seco',
    },
    {
        key: 'r30',
        a: 'Insipído',
        b: 'Descuidado',
        c: 'Culto',
        d: 'Inofensivo',
    },
    {
        key: 'r31',
        a: 'Inconsistente',
        b: 'Sin motivación',
        c: 'Detallista',
        d: 'Constante',
    },
    {
        key: 'r32',
        a: 'Ingenuo',
        b: 'Productivo',
        c: 'Quejumbroso',
        d: 'Diplomático',
    },
];
